if(!isset(weblsget("49regionalproductdate"))){ weblsset("49regionalproductdate","") }
if(!isset(weblsget("49regionalproductdescription"))){ weblsset("49regionalproductdescription","") }
if(!isset(weblsget("49regionalproductlink"))){ weblsset("49regionalproductlink","") }
if(!isset(weblsget("49regionalproductsignupbutton"))){ weblsset("49regionalproductsignupbutton","報名") }
if(!isset(weblsget("49regionalproductname"))){ weblsset("49regionalproductname","") }
if(!isset(weblsget("49regionalproductfile"))){ weblsset("49regionalproductfile","") }
if(!isset(weblsget("49regionalproductedit"))){ weblsset("49regionalproductedit","false") }
if(!isset(weblsget("49regionalproductid"))){ weblsset("49regionalgameid","") }
if(!isset(weblsget("49regionalproductvisibility"))){ weblsset("49regionalgameid","true") }