<?php
    $data=readline();
    $ans=0;
    $list=[
        "I"=>1,
        "V"=>5,
        "X"=>10,
        "L"=>50,
        "C"=>100,
        "D"=>500,
        "M"=>1000,
        "IV"=>4,
        "IX"=>9,
        "XL"=>40,
        "XC"=>90,
        "CD"=>400,
        "CM"=>900
    ];

    for($i=0;$i<strlen($data);$i=$i+1){
        if($i+1<strlen($data)&&isset($list[$data[$i].$data[$i+1]])){
            $ans=$ans+$list[$data[$i].$data[$i+1]];
            $i=$i+1;
        }else{
            $ans=$ans+$list[$data[$i]];
        }
    }

    echo($ans);
?>