<?php
    $n=trim(fgets(STDIN));
    $ans=[];
    for($i=0;$i<$n;$i=$i+1){
        $str=trim(fgets(STDIN));
        $len=strlen($str);
        $left=[];
        $star=[];
        $false=[];
        for($j=0;$j<$len;$j=$j+1){
            if($str[$j]==" "){
            }elseif($str[$j]=="("){
                $left[]=$j;
            }elseif($str[$j]==")"){
                if(count($left)>=0){
                    array_pop($left);
                }else{
                    $false=true;
                }
            }elseif($str[$j]=="*"){
                $star[]=$j;
            }else{
                $false=true;
                break;
            }
        }
        while(count($left)>0&&count($star)>0){
            if(array_slice($left,0,1)[0]<array_slice($star,0,1)[0]){
                array_pop($left);
                array_pop($star);
            }else{
                $false=true;
            }
        }
        if(count($left)==0&&!$false){
            $ans[]="Y";
        }else{
            $ans[]="N";
        }
    }
    for($i=0;$i<count($ans);$i=$i+1){
        echo($ans[$i]."\n");
    }
?>