declare function startmacossection():void
declare function divsort(card:string,sortdiv:string):HTMLElement[]
declare function docget(key:string,selector:string):HTMLElement|HTMLElement[]|null
declare function docgetid(selector:string):HTMLElement|null
declare function docgetall(selector:string):NodeListOf<HTMLElement>
declare function conlog(data:any,color?:string,size?:string,weight?:string):void
declare function isset(data:any):boolean
declare function blank(data:any):boolean
declare function weblsset(data:string,value:any):void
declare function weblsget(data:string):string|null
declare function doccreate(element:string):HTMLElement
declare function oldajax(method:string,url:string,send?:any):XMLHttpRequest
declare function lightbox(clickelement:string,element:string,lightboxhtml:(event:Event)=>string,closelement?:string|null,islightboxclosewithkeyesc?:boolean):void
declare function docappendchild(element:string,chlidelement:HTMLElement):void
declare function regexp(regexptext:string,regexpstring?:string):RegExp
declare function regexpmatch(data:string,regexptext:string,regexpstring?:string):RegExpMatchArray|null
declare function regexpreplace(data:string,replacetext:string,regexptext:string,regexpstring?:string):string
declare function ajaxdata(data:[string,any][]):FormData
declare function pagechanger(data:any[],ipp:number,key:"first"|"prev"|"next"|"end",callback:(item:any)=>void):void