<?php
    session_start();
    include("link.php");
    $rowall=$db->query("SELECT `id`, `name`, `email`, `tel`, `msg`, `img`, `createdate`, `editdate`, `isdel`, `msgnum` FROM `message`")->fetchall();
    $rowid=$db->query("SELECT `id` FROM `message`")->fetchall();
    $lenOffFile=count($rowid);
    $snum=$_POST['snum'];
    if(isset($_POST['edit'])){
        if(preg_match("/[0-9]{4}/",$snum)){
            for($i=0;$i<$lenOffFile;$i++){
                if($snum==$rowall[$i][9]){
                    $_SESSION['passcode']='pass';
                    ?>
                        <script>
                            alert("序號正確");location.href="chat.php";
                        </script>
                    <?php
                }else{
                    ?>
                        <script>
                            alert("序號錯誤");location.href="chat.php";
                        </script>
                    <?php
                }
            }
        }else{
            ?>
                <script>
                    alert("序號錯誤");location.href="chat.php";
                </script>
            <?php
        }
    }
    if(isset($_POST['del'])){
        if(preg_match("/^[0-9]{4}$/",$snum)){
            for($i=0;$i<$lenOffFile;$i++){
                if($snum==$rowall[$i][9]){
                    ?>
                        <script>
                            alert("序號正確");location.href="chat.php";
                        </script>
                    <?php
                }else{
                    ?>
                        <script>
                            alert("序號錯誤");location.href="chat.php";
                        </script>
                    <?php
                }
            }
        }else{
            ?>
                <script>
                    alert("序號錯誤");location.href="chat.php";
                </script>
            <?php
        }
    }
?>