<?php
    $n=trim(fgets(STDIN));
    $ans=[];
    $max=0;
    if((1<=$n)&&($n<=(2**31-1))){
        for($i=0;$i<$n;$i=$i+1){
            $num=trim(fgets(STDIN));
            if(isset($ans[$num])){
                $ans[$num]=$ans[$num]+1;
            }else{
                $ans[$num]=1;
            }
        }
        for($i=0;$i<count($ans);$i=$i+1){
            $value=$ans[array_keys($ans)[$i]];
            if($value>$max){
                $max=$value;
            }
        }
        if($max==1){
            echo("-1".PHP_EOL);
        }else{
            ksort($ans);
            $key=array_keys($ans);
            for($i=0;$i<count($ans);$i=$i+1){
                if($ans[$key[$i]]==$max){
                    echo($key[$i]."\n");
                }
            }
        }
    }else{
        echo("輸入未符合要求");
    }
?>