<?php
    $n=readline();
    $arr=[
        "I"=>1,
        "V"=>5,
        "X"=>10,
        "L"=>50,
        "C"=>100,
        "D"=>500,
        "M"=>1000,
        "IV"=>4,
        "IX"=>9,
        "XL"=>40,
        "XC"=>90,
        "CD"=>400,
        "CM"=>900
    ];
    $ans=0;
    for($i=0;$i<strlen($n);$i=$i+1){
        if(isset($n[$i+1])&&isset($arr[$n[$i].$n[$i+1]])){
            $ans=$ans+$arr[$n[$i].$n[$i+1]];
            $i=$i+1;
        }else{
            $ans=$ans+$arr[$n[$i]];
        }
    }
    echo($ans);
?>